# Generated by Django 3.2 on 2021-04-26 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210426_1752'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AddField(
            model_name='product',
            name='analog',
            field=models.CharField(max_length=255, null=True, verbose_name='Аналог'),
        ),
        migrations.AddField(
            model_name='product',
            name='applicability',
            field=models.CharField(max_length=255, null=True, verbose_name='Применение'),
        ),
        migrations.AddField(
            model_name='product',
            name='filter_size',
            field=models.IntegerField(default=0, verbose_name='Размер'),
        ),
        migrations.AddField(
            model_name='product',
            name='filter_volume',
            field=models.FloatField(default=0, verbose_name='Объем'),
        ),
        migrations.AddField(
            model_name='product',
            name='filter_weight',
            field=models.FloatField(default=0, verbose_name='Вес'),
        ),
        migrations.AddField(
            model_name='product',
            name='in_stock',
            field=models.BooleanField(default=False, verbose_name='В наличии'),
        ),
    ]
