# Generated by Django 3.2 on 2021-04-26 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210426_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='filter_count',
            field=models.IntegerField(default=0, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='product',
            name='filter_size',
            field=models.CharField(max_length=20, verbose_name='Размер'),
        ),
    ]
