# Generated by Django 3.2 on 2021-04-29 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210426_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='articul',
            field=models.SlugField(max_length=20, null=True, unique=True),
        ),
    ]
